[project]
name = "practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jinja2>=3.1.6",
    "langgraph>=0.4.8",
    "pydantic-ai>=0.3.1",
    "textstat>=0.7.7",
]
